### ISSUE TITLE
configuration_aliases value conversion error

### ISSUE THREAD

**Issue by gaverill-gc** [spring-media/terraform-provider-awsmt#85]
```tf
data "awsmt_playback_configuration" "example" {
  name = "example"
}
```

```
╷
│ Error: Value Conversion Error
│ 
│   with data.awsmt_playback_configuration.example,
│   on example.tf line 330, in data "awsmt_playback_configuration" "example":
│  330: data "awsmt_playback_configuration" "example" {
│ 
│ An unexpected error was encountered trying to validate the Terraform value type. This is always an error in the provider. Please report the following
│ to the provider developer:
│ 
│ tftypes.NewValue can't use map[string]tftypes.Value as a tftypes.List; expected types are: []tftypes.Value
╵
```

I believe this is due to a type mismatch regarding `configuration_aliases`. The resource has it as a [MapAttribute](https://github.com/spring-media/terraform-provider-awsmt/blob/30531b33e29b10a7700e7deda8afa26b16c53cda/awsmt/resource_playback_configuration.go#L73-L78) while the data source has it as a [ListAttribute](https://github.com/spring-media/terraform-provider-awsmt/blob/30531b33e29b10a7700e7deda8afa26b16c53cda/awsmt/data_source_playback_configuration.go#L55-L62).

**Comment by thatsddr** [comment]
Hi @gaverill-gc,

Thanks for reporting this. I have checked and you are right. It's going to be fixed in the next release :)
